### ISSUE TITLE
Up to date fork, works with unmodified CLI

### ISSUE THREAD

**Issue by luckydonald** [efaisal/pytg#17]
Hey, I forked your work, and kept it up to date here [Python with Telegram pytg2](https://github.com/luckydonald/pytg2/)
Now It works with the newest features, and **doesn't require** a **patched cli** anymore.
I update it regularly.
At time of writing, it now supports the new reply features, and link previews.

@efaisal would you be so kind to include a link to https://github.com/luckydonald/pytg2/ , please?
Cheers.

**Comment by efaisal** [comment]
Sure. I will point to your repo. @luckydonald are you interested to take
over pytg? I'm incapable to maintain it anymore.

**Comment by luckydonald** [comment]
That would be great, I'm looking forward for this.

**Comment by efaisal** [comment]
@luckydonald I've added you as collaborator and as per github doc, you should have read/write access to my pytg repo. It's been a long time I wish to remove the dependency of patched telegram-cli and I really appreciate your willingness to take over and I'm hopeful that you can take pytg to a whole new level :)

**Comment by luckydonald** [comment]
Heh, it already is on a new level, pytg2. :smile:
I am unsure how to do this merge, I was thinking about a ownership transfer to let it redirect to my repo.
Of course you would gain all the permissions on it. It just kinda feels strange to me, pushing code to an other user account.
Also I am not certain, if I should rename Pytg2 back to Pytg, as this is shorter. 
Maybe I can have your thoughts on this?
Thanks
> luckydonald

**Comment by efaisal** [comment]
I'm looking for transfer too at first. But you already forked my repo.
According to github doc the forked repo need to be removed first. So I just
went for the next best thing for now. If you could remove the forked repo
I'll be able to transfer the repo to uou.

**Comment by luckydonald** [comment]
Oh, I see. The way should be cleared now.

**Comment by luckydonald** [comment]
Not quite sure if my pytg2 repo makes problems with that, but github doesn't indicate it as forked from you (despite the fact it is cloned from you,)

**Comment by efaisal** [comment]
Ok. I'll try to transfer the repo to you.

**Comment by luckydonald** [comment]
Awesome

**Comment by luckydonald** [comment]
All Done. Thank you very much!
